config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users
  resources :users, except: [:new, :destroy, :create]
  resources :stayhotels do
    member do
      resources :reservations
    end
  end
  get '/reservations',to: 'reservations#index', as: 'reservations_index'
  get '/stayhotels/:id/reservations/new',to: 'reservations#new', as: 'reservations_new'
  post '/stayhotels/:id/reservations/confirm',to: 'reservations#confirm', as: 'reservations_confirm'
  post '/stayhotels/:id/reservations/back',to: 'reservations#back', as: 'reservations_back'
  post '/stayhotels/:id/reservations/complete',to: 'reservations#complete', as: 'reservations_complete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  #検索用
  def self.search(search,area)
    search ?
    where('room_title LIKE ? or room_intro LIKE ? or room_adress LIKE ?',"%#{(search)}%", "%#{(search)}%", "%#{(search)}%")
    .where('room_adress LIKE ?',"%#{(area)}%"): all
  end

  def value_to_boolean(search,area)
    ActiveRecord::ConnectionAdapters::Column.value_to_boolean(search, area)
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :user
    belongs_to :stayhotel

    validates :start_date, presence:true
    validates :end_date, presence:true
    validates :people_num, presence:true
    validates :people_num, numericality: { greater_than_or_equal_to: 1, less_than: 100 }, presence:true
end

app/models/stayhotel.rb
class Stayhotel < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  
  attachment :room_image
  validates :room_title, presence:true, length: { maximum: 30 }
  validates :room_intro, presence:true, length: { maximum: 400 }
  validates :room_price, presence:true
  validates :room_adress, presence:true
  validates :room_image, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :stayhotels, dependent: :destroy
  has_many :reservations, dependent: :destroy
  
  validates :username, presence:true
  validates :email, presence:true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search
  
  def set_search
    @stayhotels = Stayhotel.all.search(params[:search], params[:area])
    @count = @stayhotels.count
  end
  
  def after_sign_in_path_for(resource)
    root_path
  end
  
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	before_action :authenticate_user!
	before_action :permit_params, only: [:new, :confirm]
	before_action :stayhotel_deta_get, only: [:confirm, :complete]
	
	def index
		@reservations = Reservation.all
	end

	def new
		session.delete(:reservation)
		@reservation = Reservation.new
	end

	def back
		@reservation = Reservation.new(session[:reservation])
		session.delete(:reservation)
		redirect_to stayhotel_path
	end

	def confirm
		@reservation = current_user.reservations.new(@attr)
		@reservation.stayhotel_id = @stayhotel.id
		@people_num = @reservation["people_num"]
		start_date = @reservation["start_date"]
		end_date = @reservation["end_date"]
		@reservation.days = (end_date-start_date).to_i
		room_price = @stayhotel.room_price
		@reservation.sum_price = @reservation.days*room_price*@people_num
		session[:reservation] = @reservation
		
		if @reservation.days <= 0
			redirect_to request.referer, notice: "終了日は開始日より後の日付で設定してください。"
		elsif start_date <= Date.today
			redirect_to request.referer, notice: "本日以降の日付を選択してください"
		end
	end

	def complete
		@reservation = Reservation.create(session[:reservation])
		session.delete(:reservation)
	end

  def destroy
    reservation = Reservation.find(params[:id])
    reservation.destroy
    flash[:notice] = "予約を削除しました"
    redirect_to reservations_path
  end


	private

	def permit_params
		@attr = params.require('reservation').permit(:id,:start_date, :end_date, :people_num, :sum_price)
	end
	
	def stayhotel_deta_get
		@stayhotel = Stayhotel.find(params[:id])
	end
end

app/controllers/stayhotels_controller.rb
class StayhotelsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def new
    @stayhotel = Stayhotel.new
  end
  
  def show
    @stayhotel = Stayhotel.find(params[:id])
    @reservation = Reservation.new
  end

  def create
    @stayhotel = Stayhotel.new(stayhotel_params)
    @stayhotel.user_id = current_user.id
    if @stayhotel.save
      redirect_to stayhotel_path(@stayhotel), notice: '登録に成功しました。'
    else
      render :new
    end
  end

  def edit
    @stayhotel = Stayhotel.find(params[:id])
    if @stayhotel.user != current_user
      redirect_to stayhotel_path, alert: '不正なアクセスです。'
    end
  end
  
  def update
    @stayhotel = Stayhotel.find(params[:id])
    if @stayhotel.update(stayhotel_params)
      redirect_to stayhotel_path(@stayhotel), notice: '更新に成功しました。'
    else
      render :edit
    end
  end
  
  def destroy
    stayhotel = Stayhotel.find(params[:id])
    stayhotel.destroy
    flash[:notice] = "物件を削除しました"
    redirect_to users_path
  end

  private

  def stayhotel_params
    params.require(:stayhotel).permit(:room_title, :room_intro, :room_price, :room_adress, :room_image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @stayhotels = current_user.stayhotels.all
  end

  def show
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user), alert: "不正なアクセスです。"
    else
      render :show
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
        redirect_to edit_user_path(current_user), alert: "不正なアクセスです。"
    end
  end
  
  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path, notice: "アカウント情報を更新しました。"
    else
      render :edit
    end
  end 
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/stayhotels_helper.rb
module StayhotelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<head>
  <title>StayHotelApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag  'home', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
	<div class="main_frame">
		<div class="main_top">
			<div class="search_form">
			  <%= render 'stayhotels/search_B' %>
			</div>
		</div>
		<div class="main_bottom">
			<div class="navbox">
				<a href="/stayhotels?utf8=✓&search=&area=東京">
					<div class="region_img">
						<span>東京</span>
						<%= image_tag 'img_tokyo.jpeg', class:"r_img" %>
					</div>
				</a>
				<a href="/stayhotels?utf8=✓&search=&area=大阪">
					<div class="region_img">
						<span>大阪</span>
						<%= image_tag 'img_osaka.jpeg', class:"r_img" %>
					</div>
				</a>
				<a href="/stayhotels?utf8=✓&search=&area=京都">
					<div class="region_img">
						<span>京都</span>
						<%= image_tag 'img_kyoto.jpeg', class:"r_img" %>
					</div>
				</a>
				<a href="/stayhotels?utf8=✓&search=&area=札幌">
					<div class="region_img">
						<span>札幌</span>
						<%= image_tag 'img_sapporo.jpeg', class:"r_img" %>
					</div>
				</a>
			</div>
		</div>
	</div>
</body>

app/views/layouts/application.html.erb
<head>
  <title>StayHotelApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<header>
  <div class="h_top">
    <div class="h_left">
      <div class="app_title">
        <%= link_to root_path, class: "h_title" do %>
          <p style="font-family: cursive;">Pote Share</p>
        <% end %>	  	  
      </div>
      <div class="search">
        <%= render 'stayhotels/search_A' %>
      </div>
    </div>
    <div class="h_right">
      <div class="sign_in font_style1">
        <% if user_signed_in? %>
          <%= current_user.username %>
        <% else %>
          <%= link_to "ログイン", new_user_session_path, class: "btn01" %>
        <% end %>
      </div>
      <div class="sign_up">
        <% if user_signed_in? %>
            <div class="dropdown is-right is-hoverable">
              <div class="dropdown-trigger">
                <div class="top_profile_image" aria-haspopup="true" aria-controls="dropdown-menu">
                  <%= attachment_image_tag current_user, :profile_image, fallback: "no-image.png", class: "profile_img" %>
                </div>
              </div>
              <div class="dropdown-menu" role="menu">
              <div class="dropdown-content">
                <%= link_to "ルーム登録", new_stayhotel_path(current_user), class: "dropdown-item" %>
                <a href="#" class="dropdown-item">
                  <%= link_to "予約済みルーム登録", reservations_index_path(current_user), class: "dropdown-item" %>
                </a>
                <hr class="dropdown-divider">
                  <%= link_to "登録済みルーム一覧", users_path(current_user), class: "dropdown-item" %>
                <hr class="dropdown-divider">
                  <%= link_to "設定", user_path(current_user), class: "dropdown-item" %>
                <hr class="dropdown-divider">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </div>
        <% else %>
          <%= link_to "登録する", new_user_registration_path, class: "btn02 btn_font" %>          
        <% end %>
      </div>
    </div>
  </div>
  </div>
  <div class="h_bottom">
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
  </div>
</header>
<body>
  <main>
    <%= yield %>
 </main>
</body>
<footer>
  <div class="footer_f">
    <p>since:2022</p>
  </div>
</footer>

app/views/reservations/_errors.html.erb
<% if @reservation.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= pluralize(reservation.errors.count, "error") %></h4>
    <p><%= pluralize(reservation.errors.count, "error") %> prohibited this object from being saved: not successfully</p>
    <hr>
    <p class="mb-0">
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </p>
  </div>
<% end %>

app/views/reservations/_new.html.erb
<head>
    <%= stylesheet_link_tag  'reservations', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<%= form_for @reservation, method: :post, url: reservations_confirm_path do |form| %>
	<div class="reservation_box">
		<div class="reser_row">
		開始日<br>
		<%= form.date_field :start_date, required: true, class: "f_style2" %>
		</div>
		<div class="reser_row">
		終了日<br>
		<%= form.date_field :end_date, required: true, class: "f_style2" %>
		</div>
		<div class="reser_row">
		人数<br>
		<%= form.number_field :people_num, required: true,  in: 1..100, class: "f_style2" %>
		</div>
		<%= form.submit '予約する', class: "btn03 size100" %>
	</div>
<% end %>

app/views/reservations/complete.html.erb
<head>
    <%= stylesheet_link_tag  'users', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<div class="show_frame">
	<div class="s_f_right t_center">
		<p>ご予約ありがとうございました。</p>
		<div class="show_box t_left">
			<div class="show_row">
				<div class="r_left_2">
					予約した部屋
				</div>
				<div class="r_right">
					<%= @stayhotel.room_title %>
				</div>
			</div>
			<div class="show_row">
				<div class="r_left_2">
					開始日
				</div>
				<div class="r_right">
					<%= @reservation.start_date.strftime("%Y年 %m月 %d日") %>
				</div>
			</div>
			<div class="show_row">
				<div class="r_left_2">
					終了日
				</div>
				<div class="r_right">
					<%= @reservation.end_date.strftime("%Y年 %m月 %d日") %>
				</div>									
			</div>	
			<div class="show_row">
				<div class="r_left_2">
					価格
				</div>
				<div class="r_right">
					<%= @reservation.sum_price %>円
				</div>									
			</div>	
		</div>
	</div>
</div>

app/views/reservations/confirm.html.erb
<head>
  <%= stylesheet_link_tag  'reservations', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
	<%= form_for @reservation, method: :post, url: reservations_complete_path do |form| %>
		<div class="k_frame">
			<div class="k_main">
				<div class="k_title">予約内容確認</div>
					<div class="k_row">
						<h2>
							¥ <%= @stayhotel.room_price %>/日
						</h2>
					</div>
					<div class="k_row">
						<span>開始日</span>
						<div class="k_f">
							<%= form.text_field :start_date, readonly: true, class: "f_style2 bgc_1" %>
						</div>
					</div>
					<div class="k_row">
						<span>終了日</span>
						<div class="k_f">
							<%= form.text_field :end_date, readonly: true, class: "f_style2 bgc_1" %>
						</div>
					</div>			
					<div class="k_row bar">
						<h3>使用日数: <%= @reservation.days %>日</h3>
					</div>
					<div class="k_row bar">
						<h3>人数:<%= @reservation.people_num %>人</h3>
					</div>		
					<div class="k_row">
						<p>合計金額</p>
						<%= form.text_field :sum_price, readonly: true, class: "f_style2 bgc_1" %>
					</div>
					<div class="k_row bar">
						上記でよろしければ「予約確定」を押してください
					</div>
					<div class="k_row cen">
					<%= form_for @reservation, method: :post, url: reservations_complete_path do |form| %>
						<%= form.submit '予約確定', class: "btn03 size100" %>
					<% end %>
				</div>
					<div class="k_row cen">
					<%= form_for @reservation, method: :post, url: reservations_back_path	 do |form| %>
						<%= form.submit 'ルーム詳細に戻る', class: "btn04 size100" %>
					<% end %>
				</div>
			</div>
		</div>
	<% end %>
</body>

app/views/reservations/index.html.erb
<head>
  <%= stylesheet_link_tag  'reservations', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div class="reservation_frame">
    <h1>予約一覧</h1>
    <table>
      <tr>
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th class="width25">ルーム紹介</th>
        <th class="width8">合計金額</th>
        <th class="width8">開始日</th>
        <th class="width8">終了日</th>
        <th class="width8">予約確定日時</th>
        <th class="width5">削除</th>
      </tr>
      <% @reservations.each do |reservation| %>
      <tr>
        <td>
          <div class="img_f">
          <%= attachment_image_tag reservation.stayhotel, :room_image, fallback: "room01.jpeg", class: "img_size3" %>
          </div>
        </td>
        <td>
          <%= link_to stayhotel_path(reservation.stayhotel_id) do %>
            <%= reservation.stayhotel.room_title %>
          <% end %>
        </td>
        <td>
          <%= reservation.stayhotel.room_intro %>
        </td>
        <td>
          ¥ <%= reservation.sum_price %>
        </td>
        <td>
          <%= reservation.start_date.strftime("%Y年 %m月 %d日") %>
        </td>
        <td>
          <%= reservation.end_date.strftime("%Y年 %m月 %d日") %>
        </td>
        <td>
          <%= reservation.created_at.strftime("%Y年 %m月 %d日 %H時 %M分") %>
        </td>
        <td>
          <% if reservation.user_id == current_user.id %>
            <%= link_to "削除", reservation_path(reservation), method: :delete, data: { confirm: "本当に削除しますか？" } %>
          <% end %>      
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</body>

app/views/stayhotels/_errors.html.erb
<% if @stayhotel.errors.any? %>
  <div class="alert_outer" role="alert">
    <h2><%= pluralize(stayhotel.errors.count, "件") %> のエラーが発生したため保存されませんでした。</h2>
    <div class="b01">
      <% stayhotel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </div>
  </div>
<% end %>

app/views/stayhotels/_search_A.html.erb
<%= form_tag(stayhotels_path, method: :get, local: true) do %>
  <div class="search_box">
      <div class="s_form_outer">
        <%= icon('fa', 'map-marker', class: 's_icon') %>
        <%= text_field_tag :area, '', placeholder: 'エリア', class: "s_form_inner" %>
      </div>
      <div class="s_form_outer">
        <%= fa_icon("search", class: "s_icon") %>
        <%= text_field_tag :search, '', placeholder: 'キーワード', class: "s_form_inner" %>
      </div>
      <%= submit_tag '検索' %>
  </div>
<% end %>

app/views/stayhotels/_search_B.html.erb
<div class="f_form">
  <p>Potepan Shareでまだ体験したことのない旅をしよう</p>
  <%= form_tag(stayhotels_path, method: :get) do %>
    エリア<br>
    <%= text_field_tag :area, '', placeholder: "東京", class: "s_form_inner2" %><br>
    <%= submit_tag '探す', class: "btn03 size100" %>
  <% end %>
</div>

app/views/stayhotels/index.html.erb
<head>
<%= stylesheet_link_tag  'stayhotels', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<p class="result_title">検索結果：<%= @count %>件</p>
<div class="r_sec">
  <% @stayhotels.each do |stayhotel| %>
    <div class="r_frame f_design">
      <div class="room_info">
        <div class="r_img">
          <%= link_to stayhotel_path(stayhotel.id) do %>
          <%= attachment_image_tag stayhotel, :room_image, fallback: "room01.jpeg", class: "img_size" %>
        </div>
        <div class="r_title">
          <%= stayhotel.room_title %>
          <% end %>
        </div>
        <div class="r_adress">
          <%= stayhotel.room_adress %>
        </div>
        <div class="r_price">
          ¥ <%= stayhotel.room_price %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/stayhotels/new.html.erb
<head>
  <%= stylesheet_link_tag  'users', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<%= render "/stayhotels/errors", stayhotel: @stayhotel %>
	<div class="show_frame">
		<div class="s_f_left">
			<ul>
				<li class="link_on">
				  <%= link_to "新規登録", new_stayhotel_path %>
				</li>
			</ul>
		</div>
		<div class="s_f_right">
			<div class="show_box">
				<span>ルーム情報登録</span>
				<%= form_for @stayhotel do |f| %>	
					<div class="show_row top_bar">
						<div class="r_left">
							<%= f.label :room_title, "ルーム名" %>
						</div>
						<div class="r_right">
						  <%= f.text_field :room_title, class: "f_style", placeholder: "ルーム名を入力", required: true %>
						</div>									
					</div>
					<div class="show_row">
						<div class="r_left">
						  <%= f.label :room_intro, "ルーム紹介" %>
						</div>
						<div class="r_right">
							<%= f.text_area :room_intro, class: "f_style f_height", placeholder: "ルーム説明を入力", required: true %>
						</div>									
				  </div>
					<div class="show_row">
						<div class="r_left">						
							<%= f.label :room_price, "料金" %>
						</div>
						<div class="r_right">
							<%= f.text_field :room_price, class: "f_style", placeholder: "一日あたりの料金を入力", required: true %>
						</div>									
					</div>	
					<div class="show_row">
						<div class="r_left">						
							<%= f.label :room_adress, "住所" %>
						</div>
						<div class="r_right">
							<%= f.text_field :room_adress, class: "f_style", placeholder: "住所を入力", required: true %>
						</div>									
					</div>
					<div class="show_row">
						<div class="r_left">						
							<%= f.label :room_title, "ルーム画像" %>
						</div>
						<div class="r_right">
							<%= f.attachment_field :room_image, required: true %>
						</div>									
					</div>		
				  <%= f.submit "登録", class: "btn03 btn_120 is-success" %>
				<% end %>	
			</div>
		</div>
	</div>
</body>

app/views/stayhotels/show.html.erb
<head>
	<%= stylesheet_link_tag  'stayhotels', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<%= render "/reservations/errors", reservation: @reservation %>
<div class="s_frame">
	<div class="s_frame2">
		<div class="left_f">
			<%= attachment_image_tag @stayhotel, :room_image, class: "img_size2" %>
			<div class="room_info1">
				<div class="usericon">
					<%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "profile_img" %>
				</div>
				<div class="title-adress">
					<h2><%= @stayhotel.room_title %></h2>
					<p><%= @stayhotel.room_adress %></p>
				</div>
			</div>
			<div class="room_info2">
				<%= simple_format @stayhotel.room_intro %>
			</div>	
		</div>
		<div class="right_f">
			<div class="pa_f">
				<p>￥<%= @stayhotel.room_price %> / 日</p>
				<div class="partial">
					<%= render 'reservations/new', reservation: @reservation %>
				</div>
			</div>
		</div>	
	</div>
</div>

app/views/users/_errors.html.erb
<% if @user.errors.any? %>
	<div class="alert_outer">
		<h2><%= pluralize(@user.errors.count, "件") %> のエラーが発生したため保存されませんでした。</h2>
		<ul>
	 		<% @user.errors.full_messages.each do |message| %>
	 		<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/users/edit.html.erb
<head>
  <title>StayHotelApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag  'users', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<%= render "users/errors", user: @user %>
	<div class="show_frame">
		<div class="s_f_left">
			<ul>
				<li>
				  <%= link_to "アカウント", user_path %>
				</li>
				<li class="link_on">
				  <%= link_to "プロフィール", edit_user_path %>
				</li>			
			</ul>
		</div>
		<div class="s_f_right">
			<div class="show_box">
				<span>プロフィール</span>
				<div class="r_cen">
					<%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "edit_profile" %>
				</div>
				<%= form_for @user do |f| %>	
					<div class="show_row">
						<div class="r_left">
							<%= f.label :profile_image, "アイコン画像" %>
						</div>
						<div class="r_right">
							<%= f.attachment_field :profile_image  %>
						</div>									
					</div>
					<div class="show_row">
						<div class="r_left">
							<%= f.label :username, "ユーザー名" %>
						</div>
						<div class="r_right">
							<%= f.text_field :username %>
						</div>									
					</div>
					<div class="show_row">
						<div class="r_left">						
							<%= f.label :profile, "プロフィール" %>
						</div>
						<div class="r_right">
							<%= f.text_area :profile, class: "textarea" %>
						</div>									
					</div>
					<%= f.submit "更新", class: "btn03 is-success" %>
				<% end %>				
			</div>
		</div>
	</div>
</body>

app/views/users/index.html.erb
<head>
  <%= stylesheet_link_tag  'reservations', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <div class="room_frame">
    <h1>登録済みルーム一覧</h1>
    <table>
      <tr>
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>料金</th>
        <th>作成日</th>
        <th>削除</th>
      </tr>
      <% @stayhotels.each do |stayhotel| %>
      <tr>
        <td>
          <div class="img_f">
            <%= attachment_image_tag stayhotel, :room_image, fallback: "no-image.png", class: "img_size3" %>
          </div>
        </td>
        <td>
          <%= link_to stayhotel_path(stayhotel.id) do %>
            <%= stayhotel.room_title %>
          <% end %>
        </td>
        <td>
          <%= stayhotel.room_intro %>
        </td>
        <td>
          ￥<%= stayhotel.room_price %>
        </td>
        <td>
          <%= stayhotel.created_at.strftime("%Y-%m-%d %H:%M") %>
        </td>
        <td>
          <% if stayhotel.user_id == current_user.id %>
            <%= link_to "削除", stayhotel_path(stayhotel), method: :delete, data: {confirm: "削除しますか？"} %>
          <% end %>  
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</body>

app/views/users/show.html.erb
<head>
  <%= stylesheet_link_tag  'users', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
  <body>
  	<div class="show_frame">
  		<div class="s_f_left">
  			<ul>
  				<li class="link_on">
				    <%= link_to "アカウント", user_path %>
  				</li>
  				<li>
 				    <%= link_to "プロフィール", edit_user_path %> 				
  				</li>			
  			</ul>
  		</div>
  		<div class="s_f_right">
  			<div class="show_box">
  				<span>アカウント</span>
  				<div class="show_row horizontal padding5">
  					<div class="r_left_2">
  					メールアドレス
  					</div>
  					<div class="r_right">
  					  <%= @user.email %>
  					</div>									
  				</div>
  				<div class="show_row horizontal padding5">
  					<div class="r_left_2">
  					パスワード
  					</div>
  					<div class="r_right">
  					  ********
  					</div>									
  				</div>	
  				<div class="show_row2 horizontal">
  				  <%= link_to "編集", edit_user_registration_path, class: "btn03 btn_200" %> 		
  			  </div>
  			</div>
  		</div>
  	</div>
  </body>
  